import type { DB } from "./types";

const img = (q: string) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=600&q=70`;

export function seedDB(): DB {
  return {
    settings: {
      siteName: "TKG Snacks",
      logoUrl: "",
      phone: "01581029536",
      location: "Thakurgaon",
      deliveryCharge: 40,
      adminPassword: "qwertyuiop",
    },
    categories: [
      { id: "c1", name: "Fast Food" },
      { id: "c2", name: "Biryani" },
      { id: "c3", name: "Pizza" },
      { id: "c4", name: "Snacks" },
      { id: "c5", name: "Drinks" },
      { id: "c6", name: "Bakery" },
    ],
    shops: [
      {
        id: "s1",
        name: "Thakurgaon Burger House",
        logo: img("photo-1568901346375-23c9450c58cd"),
        ownerPhone: "01711000001",
        address: "Chowrasta, Thakurgaon",
        active: true,
        password: "shop123",
      },
      {
        id: "s2",
        name: "Kacchi Ghor",
        logo: img("photo-1563379091339-03b21ab4a4f8"),
        ownerPhone: "01711000002",
        address: "College Road, Thakurgaon",
        active: true,
        password: "shop123",
      },
      {
        id: "s3",
        name: "Golden Bakery",
        logo: img("photo-1509440159596-0249088772ff"),
        ownerPhone: "01711000003",
        address: "Hazipara, Thakurgaon",
        active: true,
        password: "shop123",
      },
    ],
    items: [
      {
        id: "i1",
        shopId: "s1",
        categoryId: "c1",
        name: "Cheese Beef Burger",
        description: "Juicy grilled beef patty with melted cheddar and house sauce.",
        ingredients: "Beef patty, cheddar, lettuce, tomato, sesame bun, special sauce",
        price: 220,
        image: img("photo-1571091718767-18b5b1457add"),
        inStock: true,
        rating: 4.7,
      },
      {
        id: "i2",
        shopId: "s1",
        categoryId: "c4",
        name: "Crispy French Fries",
        description: "Golden crispy fries tossed with peri peri seasoning.",
        ingredients: "Potato, salt, peri peri mix, sunflower oil",
        price: 90,
        image: img("photo-1573080496219-bb080dd4f877"),
        inStock: true,
        rating: 4.4,
      },
      {
        id: "i3",
        shopId: "s2",
        categoryId: "c2",
        name: "Mutton Kacchi Biryani",
        description: "Slow-cooked aromatic kacchi biryani with tender mutton.",
        ingredients: "Basmati rice, mutton, yogurt, ghee, saffron, spices",
        price: 380,
        image: img("photo-1563379091339-03b21ab4a4f8"),
        inStock: true,
        rating: 4.9,
      },
      {
        id: "i4",
        shopId: "s2",
        categoryId: "c5",
        name: "Borhani Glass",
        description: "Traditional spiced yogurt drink, perfect with biryani.",
        ingredients: "Yogurt, mint, green chili, black salt",
        price: 60,
        image: img("photo-1608270586620-248524c67de9"),
        inStock: true,
        rating: 4.3,
      },
      {
        id: "i5",
        shopId: "s3",
        categoryId: "c6",
        name: "Butter Croissant",
        description: "Flaky French style croissant baked fresh every morning.",
        ingredients: "Flour, butter, yeast, milk, sugar",
        price: 70,
        image: img("photo-1555507036-ab1f4038808a"),
        inStock: true,
        rating: 4.6,
      },
      {
        id: "i6",
        shopId: "s3",
        categoryId: "c3",
        name: "Farmhouse Pizza",
        description: "Loaded veggie pizza with mozzarella on a thin crust.",
        ingredients: "Dough, mozzarella, capsicum, onion, mushroom, tomato sauce",
        price: 450,
        image: img("photo-1513104890138-7c749659a591"),
        inStock: true,
        rating: 4.5,
      },
    ],
    riders: [
      {
        id: "r1",
        name: "Rakib Hasan",
        phone: "01811000001",
        vehicle: "Motorcycle",
        license: "TKG-DL-4421",
        password: "rider123",
        status: "Available",
      },
      {
        id: "r2",
        name: "Sabbir Ahmed",
        phone: "01811000002",
        vehicle: "Bicycle",
        license: "TKG-DL-7712",
        password: "rider123",
        status: "Offline",
      },
    ],
    orders: [],
  };
}
